import json
import dash_leaflet as dl

# Establish which countries belong to which cultural region
countries_by_region = {
    "Anglo World": [
        "United Kingdom",
        "Australia",
        "New Zealand",
        "Ireland",
        "United States",
        "Canada",
    ],
    "Europe": [
        "Poland",
        "Czechia",
        "Hungary",
        "Bulgaria",
        "Serbia",
        "Slovakia",
        "Croatia",
        "Bosnia & Herzegovina",
        "North Macedonia",
        "Slovenia",
        "Montenegro",
        "Germany",
        "France",
        "Netherlands",
        "Belgium",
        "Austria",
        "Switzerland",
        "Italy",
        "Spain",
        "Portugal",
        "Luxembourg",
        "Sweden",
        "Denmark",
        "Finland",
        "Norway",
        "Lithuania",
        "Latvia",
        "Estonia",
        "Greece",
        "Cyprus",
        "Iceland",
        "Greenland",
        "Romania",
        "Albania",
    ],
    "North Eurasia": ["Russia", "Ukraine", "Belarus", "Georgia", "Armenia", "Moldova"],
    "Central & South America": [
        "Jamaica",
        "Trinidad & Tobago",
        "Bahamas",
        "Guyana",
        "Suriname",
        "Belize",
        "Mexico",
        "Colombia",
        "Peru",
        "Venezuela",
        "Guatemala",
        "Ecuador",
        "Dominican Rep.",
        "Honduras",
        "Nicaragua",
        "El Salvador",
        "Costa Rica",
        "Panama",
        "Puerto Rico",
        "Argentina",
        "Chile",
        "Uruguay",
        "Bolivia",
        "Paraguay",
        "Cuba",
        "Brazil",
        "French Guiana",
        "Cape Verde",
        "Mauritius",
        "Reunion",
    ],
    "Middle East & North Africa": [
        "Saudi Arabia",
        "U.A.E.",
        "Kuwait",
        "Oman",
        "Qatar",
        "Bahrain",
        "Egypt",
        "Iraq",
        "Syria",
        "Jordan",
        "Libya",
        "Palestine",
        "Morocco",
        "Algeria",
        "Tunisia",
        "Yemen",
        "Lebanon",
        "Israel",
        "Iran",
        "Afghanistan",
        "Pakistan",
    ],
    "Sahel & Sub-Saharan Africa": [
        "Sudan",
        "Mauritania",
        "Niger",
        "Mali",
        "Chad",
        "Somalia",
        "Djibouti",
        "Ivory Coast",
        "Burkina Faso",
        "Senegal",
        "Guinea",
        "Benin",
        "Togo",
        "Gambia",
        "Guinea-Bissau",
        "Tanzania",
        "Kenya",
        "Uganda",
        "Malawi",
        "Zambia",
        "Rwanda",
        "Burundi",
        "D.R. Congo",
        "Cameroon",
        "Central African Rep.",
        "Rep. Congo",
        "Gabon",
        "Equatorial Guinea",
        "Nigeria",
        "Ghana",
        "Sierra Leone",
        "Liberia",
        "Mozambique",
        "Angola",
        "Madagascar",
        "South Sudan",
        "Haiti",
        "South Africa",
        "Namibia",
        "Botswana",
        "Lesotho",
        "Eswatini",
        "Zimbabwe",
        "Ethiopia",
        "Eritrea",
    ],
    "South Asia": ["India", "Nepal", "Bhutan", "Bangladesh", "Sri Lanka"],
    "Central Asia": [
        "Uzbekistan",
        "Kazakhstan",
        "Kyrgyzstan",
        "Turkmenistan",
        "Turkey",
        "Azerbaijan",
        "Tajikistan",
        "Mongolia",
    ],
    "East Asia": ["China", "Taiwan", "Japan", "South Korea", "North Korea"],
    "Southeast Asia & South Pacific": [
        "Cambodia",
        "Laos",
        "Myanmar",
        "Thailand",
        "Vietnam",
        "Singapore",
        "Malaysia",
        "Brunei",
        "Indonesia",
        "Philippines",
        "Papua New Guinea",
        "Solomon Islands",
        "Vanuatu",
        "New Caledonia",
        "Fiji",
        "Samoa",
        "French Polynesia",
        "East Timor",
    ],
}

# Mapping of identifiers to colors.
# region_colors = {
#  "Anglo World": '#27BEB6',
#  "Europe": '#518BC9',
#  "North Eurasia": '#8B91F5',
#  "Central & South America": '#F4AE1A',
#  "Middle East & North Africa": '#EFD31A',
#  "Sahel & Sub-Saharan Africa": '#F36B28',
#  "South Asia": '#67BF6B',
#  "Central Asia": '#EC468B',
#  "East Asia": '#F5A051',
#  "Southeast Asia & South Pacific": '#BAF87F',
#  "Antarctica": '#000000'
# }
region_colors = {
    "Anglo World": "#b3de69",
    "Europe": "#8dd3c7",
    "North Eurasia": "#80b1d3",
    "Central & South America": "#fb8072",
    "Middle East & North Africa": "#ffed6f",
    "Sahel & Sub-Saharan Africa": "#fdb462",
    "South Asia": "#ffffb3",
    "Central Asia": "#B3B9FF",
    "East Asia": "#bc80bd",
    "Southeast Asia & South Pacific": "#fccde5",
    "Antarctica": "#000000",
}

# Open region GeoJSON
with open("cultural_regions_simplified.geojson", "tr") as fi:
    regions = json.load(fi)

# Create a GeoJSON layer for each feature (polygon) in the GeoJSON file and assign the color from the dictionary
layers = [
    dl.TileLayer(
        url="http://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png",
        attribution="© OpenStreetMap contributors, © CartoDB",
    )
]
for feature in regions["features"]:
    # Replace 'id' with the name of the property that holds your identifiers
    identifier = feature["properties"]["Region"]
    color = region_colors.get(
        identifier, "#000000"
    )  # default to black if the id is not found in the dictionary
    layers.append(
        dl.GeoJSON(
            data=dict(type="FeatureCollection", features=[feature]),
            options=dict(style=dict(color=color, fillColor=color, fillOpacity=1)),
        )
    )

# Add layer that later contains the map marker
layers.append(dl.LayerGroup(id="layer"))
